export const API_PATHS = {
  RECIPES: "/api/recipes",
  RECIPES_CATEGORIES: "/api/recipes/categories",
  RECIPES_AUTOCOMPLETE: "/api/recipes/autocomplete",
  RECIPES_SEARCH_BY_INGREDIENTS: "/api/recipes/search-by-ingredients",
  RECIPE_REQUESTS: "/api/recipe-requests",
  REPORTS: "/api/reports",
  INGREDIENTS: "/api/ingredients",
  CHAT: "/api/chat",
  CHAT_HISTORY: "/api/chat/history",
  USER_ALLERGIES: "/api/user/allergies",
  USER_FAVORITES: "/api/user/favorites",
  YOUTUBE: (videoId: string) => `/api/youtube/${videoId}`,
  RECIPE_BY_SLUG: (slug: string) => `/api/recipes/${slug}`,
  RECIPE_REQUEST_BY_ID: (id: string | number) => `/api/recipe-requests/${id}`,
  ADMIN_LOGIN: "/api/admin/login",
  ADMIN_RECIPE_BY_ID: (id: string | number) => `/api/admin/recipes/${id}`,
  ADMIN_RECIPES: "/api/admin/recipes",
  ADMIN_INGREDIENT_BY_ID: (id: string | number) =>
    `/api/admin/ingredients/${id}`,
  ADMIN_INGREDIENTS: "/api/admin/ingredients",
  ADMIN_USER_BY_ID: (id: string | number) => `/api/admin/users/${id}`,
  ADMIN_USERS: "/api/admin/users",
  REPORT_BY_ID: (id: string | number) => `/api/reports/${id}`,
};
